[package]
name = "app"
version = "0.1.0"
authors = ["sorenhoyer <soren@codeish.com>"]

[dependencies]
app_registry = { path = "../app_registry" }
app_trait = { path = "../app_trait" }
app_model = { path = "../app_model" }
rouille = "*"
serde_json = "*"