[package]
name = "app_registry"
version = "0.1.0"
authors = ["sorenhoyer <soren@codeish.com>"]

[dependencies]
lazy_static = "0.1.15"
app_trait = { "path" = "../app_trait" }
app_model = { "path" = "../app_model" }